### ISSUE TITLE
Passwordless Authentication Issue

### ISSUE THREAD

**Issue by cwesterhold** [ened/flutter_plugin_auth0_native#1]
I love the plugin! After waiting around for Auth0 to put something out, its great that you put this together.

I am running into an issue with the passwordless Auth. The passwordlessWithSMS() method works great but the secondary call to loginWithPhoneNumber() is getting a 404. It is posting to /oauth/ro instead of /oauth/token.

In the Auth0 API docs, it provides a Postman collection that has the oauth/ro as the post... but it doesnt work there either.  I have tested it in Postman and it works great with the /oauth/token.

![image](https://user-images.githubusercontent.com/43251690/86066072-c38cb400-ba36-11ea-8eec-03db52c4166b.png)

The token expired before I could get it all working but its getting past the 404 error.

I appreciate any help you can provide.

**Comment by cwesterhold** [comment]
It also looks like its using 'password' on the post and it should be using 'otp'.    Here is a snippet from the auth0 docs.

![image](https://user-images.githubusercontent.com/43251690/86059897-5292cf80-ba29-11ea-89fc-75e46e1e57e9.png)

**Comment by ened** [comment]
Have you enabled this one:

<img width="881" alt="Screenshot 2020-06-30 at 10 01 44" src="https://user-images.githubusercontent.com/269860/86106644-b6180e00-bab8-11ea-920e-ee05ae31c567.png">

We are using SMS OTP with this exact code now in a production App, without problems.
Therefore, I suspect the issue is with your tenant / application configuration.

**Comment by ened** [comment]
Also, I suggest to pay attention to the OIDC flag. If your App is OIDC conformant, but the auth0 config in the SDK is not, there may be a mismatch on the endpoints.

**Comment by cwesterhold** [comment]
Thank you very much for the information.  I am new to flutter but have been using the passwordless flow with angular for a number of years.  It sounds like I need to understand more about how Auth0 needs to be configured for native.

Thanks again for your time.

**Comment by ened** [comment]
My pleasure. Please reopen ticket if you find other problems.
The example App in this project is a great place to start.

**Comment by cwesterhold** [comment]
![image](https://user-images.githubusercontent.com/43251690/86149148-304c9080-bac1-11ea-9d11-3f73f073d37f.png)

I appreciate pointing me to the OIDC flag.  the /ro endpoint is the non-conformant flow with the /token being the conforming flow.  Do you have any plans on supporting the conforming flow?  I have been looking through the code to see if I could help, but I am MEAN stack dev and dont know much java.   Based on what Auth0 has in their docs, they wont be supporting the legacy flow with any new features or support, so it looks like we will all have to migrate eventually.

I have switched off the OIDC compliant switch in the Auth0 app settings but cant seem to get it to change to the /ro endpoint.  Any idea how I might be able to get that?    

The sample app is fantastic and it helped to get things up and running.   Again, I really appreciate your efforts on this.

**Comment by ened** [comment]
I think the key question is whether the "confirming" flow is supported by the native SDKs in those separate methods, or whether the OTP login is handled through the web interface (e.g. within the safari / chrome window).

**Comment by cwesterhold** [comment]
I figured it out....  On the Initialize call.

![image](https://user-images.githubusercontent.com/43251690/86155188-ae149a00-bac9-11ea-80ab-31ab4a1a0c52.png)


You have the oidc set to false and is set to optional.    Switching this to true changes the endpoint to use the /oauth/token.  This solves the issue and everything is working correctly now.  Hopefully this will save others some time.  

Thanks again for all of your efforts on getting this up and running!  Cheers!

**Comment by ened** [comment]
Nice! You’re very welcome. You can see a lot of parameter and the readme file itself could use documentation.

Feel free to send PRs that extend them as you go along.
